### ISSUE TITLE
linux foundation partnership: code of conduct

### ISSUE THREAD

**Issue by bghira** [Open-Model-Initiative/OMI-Training-Pipeline#1]
hello, since the integration of OMI into the Linux Foundation, I was wondering if this indicates a plan to take their Code of Conduct seriously.

if so, can we have the earlier user bans from the OMI discord reviewed? as they were unilateral decisions by the CEO of Invoke, without following through the covenant details or having any kind of official review / appeals process.

I'm hoping this is a sign that the project is beginning to mature and move in a better community-oriented direction, and that's welcomed.

**Comment by hipsterusername** [comment]
Hey @bghira  -- 

Thanks for raising the conversation again. The decision was actually made by the entirety of the OMI moderation team based on your behavior in the discord (with active discussion and inclusion of new moderators due to type of behavior being demonstrated).

Per the LF and OMI Code of Conduct:

- Treat each other with respect, professionalism, fairness, and sensitivity to our many differences and strengths, including in situations of high pressure and urgency.

This was violated numerous times, due to disagreements in the approach the OMI was taking. The behavior was both disrespectful and unprofessional. 

However, if you'd like to appeal and get involved again in the work the OMI is doing, we'd be happy to have you. We respect the work you do, but need to ensure the community is a place for respectful dialogue.

Feel free to reach out!

**Comment by bghira** [comment]
can you show the chat logs from the Discord server that demonstrate the rule being violated?

**Comment by hipsterusername** [comment]
![image](https://github.com/user-attachments/assets/c40c6968-6366-4717-8687-0ed10b08aa56)
![image](https://github.com/user-attachments/assets/a4f7b4ea-8040-4cf2-8f65-f6300397570c)

Offensive language, general adversarial attitude and tone towards good-intentioned and good-faith efforts to prevent CSAM, and then alluding (and then subsequently following the ban, outside of the community, explicitly stating) that the model was planning be used to generate images in the vein of bestiality. 

The above are not mature, respectful, or professional ways to engage. This, combined with the fact that multiple moderators have noted multiple communities from which you've been banned for code of conduct violations, supported the decision to ban from the channel to maintain order.

As noted in my previous post - if you're willing to make good faith efforts to participate in the community without violating the code of conduct, you are an obvious contributor to the open-source ecosystem, and would be a valuable contributor to the project.

**Comment by bghira** [comment]
i don't think i ever stated that it was planned to be used for bestiality, not even mentioned once. that's an overreaction on your part and perhaps a little bit of projection.

what was actually happening was a number of people including myself trying to find the intent and line in the sand behind "no kids in the dataset"

you're honestly telling me you don't see how this is a legitimate line of discussion? you don't remember the users on Reddit who downvoted you to oblivion and said "you didn't even answer the questions"?

**Comment by hipsterusername** [comment]
It’s not an overreaction, given the statement you’ve made and the folks who’ve joined the discord saying they’ve been told the same. I recognize it can be easy to be frustrated and say things that are jabs, but the behavior was very clearly adversarial in discord.

The line of discussion itself was valid, and continued long after you were banned, ultimately resulting in us changing course for dataset plans.

The manner in which you maintained discourse was not in line with the code of conduct. I’ve been attempting to provide a reasonable path to your inclusion in the community - just looking to have you confirm you’ll act in good faith to adhere to it.

We don’t want or appreciate drama. This group is too busy for it.

**Comment by bghira** [comment]
i've still been trying to find the things that i said that were in a manner unfit for the community. you only cherry-picked a single statement from me without any greater context. but it's not like i can go and retrieve the context for you, because i'm banned. and you have control over which parts of the context are even included, because of your admin powers and the ability to simply remove others' comments.

i wasn't looking for inclusion, i was simply looking for a hint of whether anything has changed wrt you being in a sort of dictatorial position over the project, and this thread confirms that

**Comment by hipsterusername** [comment]
I havent deleted any of your comments from discord, and am simply pointing to a few comments highlighting the tone and nature of the feedback you provided.

However I can see that this may not be a fruitful discussion, since you’re not interested in the project. 

Wish you the best with your work.
